#!/bin/sh
[ -f /etc/banner ] && cat /etc/banner

export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
export HOME=${HOME:-/root}
export PS1='[\[\033[35;1m\]\u\[\033[0m\]@\[\033[31;1m\]\h\[\033\[0m\]:\[\033[32;1m\]$PWD\[\033[0m\]]\$'

alias hd='cd /data/UsbDisk1/Volume1/'
alias ll='ls -al'
alias tarxz='tar -xvzf'
alias tarcz='tar -cvzf'
alias es='/etc/etmsh start'
alias et='/etc/etmsh stop'
alias rf='reboot -f'
alias ms='/etc/init.d/monit start'
alias mt='/etc/init.d/monit stop'
d="/etc/init.d/"


[ -x /bin/more ] || alias more=less
[ -x /usr/bin/vim ] && alias vi=vim || alias vim=vi

[ -z "$KSH_VERSION" -o \! -s /etc/mkshrc ] || . /etc/mkshrc

[ -x /usr/bin/arp ] || arp() { cat /proc/net/arp; }
[ -x /usr/bin/ldd ] || ldd() { LD_TRACE_LOADED_OBJECTS=1 $*; }
